### ISSUE TITLE
Missing fonts/text in beta version Android

### ISSUE THREAD

**Issue by vindard** [GaloyMoney/galoy-mobile#317] opened 2021-12-01 14:59 UTC
## Description
Screenshots attached to illustrate, `v1.6.0 build 287`

**Model:** LE2115
**Build number:** Oxygen OS 11.2.9.9.LE25AA

## Screenshots

![photo_2021-12-01_08-56-24](https://user-images.githubusercontent.com/17693119/144258078-c8ac1bf3-c85d-4992-ba95-6f0f09984b53.jpg)

![photo_2021-12-01_08-56-29](https://user-images.githubusercontent.com/17693119/144258082-4bb0ee33-83ab-4b52-ba0b-9a559e271c7d.jpg)

![photo_2021-12-01_08-56-33](https://user-images.githubusercontent.com/17693119/144258083-3b617dbb-1232-4fba-b675-59871fe8298a.jpg)

**Comment by daviroo** [comment] 2021-12-01 15:05
This actually looks like a translation issue after seeing the error on the settings screen.

**Comment by vindard** [comment] 2021-12-01 17:16
There's also a bunch of missing things on the settings screen when I'm actually logged in

![photo_2021-12-01_11-15-34](https://user-images.githubusercontent.com/17693119/144281686-d73cf6a1-f76b-45d4-b39d-daabb96f146c.jpg)

**Comment by krtk6160** [comment] 2021-12-07 05:33
I can confirm that I can reproduce the same issues (except the missing country flag icon) with `v1.6.0 build 289` on Android 12

**Comment by daviroo** [comment] 2021-12-07 15:22
This was fixed in #328

**Closed by daviroo** 2021-12-07 15:22 UTC
