### ISSUE TITLE
Scan from send screen?

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-mobile#109] opened 2021-07-23 23:11 UTC
From https://twitter.com/pablof7z

One piece of feedback: I’ve noticed myself and others going to “Send” to scan a QR code and not finding anything  to do it there, I know it’s under “scan qr” on the main screen but probably worthwhile linking it from the send screen too 😁

**Comment by jrbuhl93** [comment] 2021-08-09 17:16
Duplicate of #143

**Closed by jrbuhl93** 2021-08-09 17:16 UTC
Labels: duplicate
